version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
